var dico_fr = {
    "Order"  : "Commander",
	"Back"  : "Retour",
	"Cart"  : "Panier",
	"Menu"  : "Menu",
	"Pickup"  : "Votre commande",
	"Menus"  : "Menus",
	"Drinks"  : "Boissons",
	"Sides"  : "Accompagnement",
	"Desserts"  : "Desserts",	
	"Total VAT:"  : "TOTAL TTC :",
	"Please choose your items"  : "Remplissez votre panier!",
	"Empty cart"  : "Vider le panier",
	"Checkout"  : "Commander",
	"When do you want to pick it up ?" : "Quand voulez-vous venir?",
	"Our restaurant is open from:" : "Notre restaurant est ouvert du ...",
	"Your phone number:" : "Votre téléphone :",
	"Your email:" : "Votre email :", 
	"Your name:" : "Votre prénom :", 
	"Any comment ?" : "Des commentaires ?", 
	"Total order:" : "Total TTC :",
	"Please select a date" : "Choisissez une date",
	"Please select a time" : "Choisissez une heure",
	"Please specify your name." : "Veuillez entrer votre nom.",
	"We need your email address to contact you." : "Veuillez entrer votre adresse email.",
	"Your email address must be in the format of name@domain.com." : "Votre adresse email doit etre de la forme nom@domaine.com.",
	"We need your phone number to contact you." : "Nous avons besoin de votre numéro de téléphone (pas de spam!).",
	"Please select a date." : "Choisissez une date de retrait.",
	"Please select a time." : "Choisissez une heure de retrait.",
	"vegan cheese" : "fromage végétal vegan",
	"gluten free option" : "option sans gluten",
	"Vegan cheese:" : "Fromage végétal vegan :",
	"Gluten free option:" : "Option sans gluten :",
	"without" : "avec",
	"with" : "sans",
	"Products" : "Produits",
	"Price" : "Prix",
	"Qty" : "Qte",
	"SubTotal" : "Sous Total",
	"Remove" : "Supprimer",
	"Sauce:" : "Sauce : ",
	"Side:" : "Accompagnement :",
	"Drink:" : "Boisson :",
	"Dessert:" : "Dessert :",
	"Add to Cart" : "Ajouter au panier",
	"Menu" : "Menu",
	"Burger:" : "Burger :",
	"none" : "aucune",
	"January" : "Janvier",
	"February" : "Février",
	"March" : "Mars",
	"April" : "Avril",
	"May" : "Mai",
	"June" : "Juin",
	"July" : "Juillet",
	"August" : "Août",
	"September" : "Septembre",
	"October" : "Octobre",
	"November" : "Novembre",
	"December" : "Décembre",
	"Today" : "Aujourd'hui",
	"Clear" : "Effacer",
	"Mon" : "Lun",
	"Tue" : "Mar",
	"Wed" : "Mer",
	"Fri" : "Jeu",
	"Thu" : "Ven",
	"Sat" : "Sam",
	"Sun" : "Dim",
	"You might want to order something before considering checkout." : "Peut-etre voudriez-vous ajouter des produits avant de commander?",
	"Your basket is too old, please go back to home and make a new one." : "Votre panier est trop ancien, videz le et commander à nouveau.",
	"Communication server fail, are you connected to the Internet?" : "Erreur de connexion, etes vous toujours connecté?",
	"You must use a recent device to use this service." : "Vous devez utiliser un appareil récent pour accéder à ce service.",
	"Cannot load data, are you connected to the Internet?" : "Impossible de charger les données, etes-vous connecté à l'Internet?",
	"burger + side + drink"  : "Petit menu : burger + frites ou salade + boisson",
	"burger + side + drink + dessert"  : "Grand menu : burger + frites ou salade + boisson + dessert",
	"Select, purchase and come pick up your order at the time of your choice!" : "Choisissez, régler et venez récupérer votre commande à l'heure de votre choix!",
	"Hank, 55 rue des Archives 75003 Paris, open 7/7 from 12h to 22h." : "Hank, 55 rue des Archives 75003 Paris, ouvert du 7/7 de 12h à 22h."
	 
}

var dico = {
    "Order"  : "Order",
	"Back"  : "Back",
	"Cart"  : "Cart",
	"Menu"  : "Menu",
	"Pickup"  : "Pickup",
	"Menus"  : "Menus",
	"Drinks"  : "Drinks",
	"Sides"  : "Sides",
	"Desserts"  : "Desserts",	
	"Total VAT:"  : "TOTAL VAT :",
	"Please choose your items"  : "Please choose your items.",
	"Empty cart"  : "Empty cart",
	"Checkout"  : "Checkout",
	"When do you want to pick it up ?" : "When do you want to pick it up ?",
	"Our restaurant is open from:" : "Our restaurant is open from",
	"Your phone number:" : "Your phone number:",
	"Your email:" : "Your email:", 
	"Your name:" : "Your name:", 
	"Any comment ?" : "Any comment ?", 
	"Total order:" : "Total order:",
	"Please select a date" : "Please select a date",
	"Please select a time" : "Please select a time",
	"Please specify your name." : "Please specify your name.",
	"We need your email address to contact you." : "We need your email address to contact you.",
	"Your email address must be in the format of name@domain.com." : "Your email address must be in the format of name@domain.com.",
	"We need your phone number to contact you." : "We need your phone number to contact you.",
	"Please select a date." : "Please select a date.",
	"Please select a time." : "Please select a time.",
	"vegan cheese" : "vegan cheese",
	"gluten free option" : "gluten free option",
	"Vegan cheese:" : "Vegan cheese:",
	"Gluten free option:" : "Gluten free option:",
	"without" : "without",
	"with" : "with",
	"Products" : "Products",
	"Price" : "Price",
	"Qty" : "Qty",
	"SubTotal" : "SubTotal",
	"Remove" : "Remove",
	"Sauce:" : "Sauce : ",
	"Side:" : "Side:",
	"Drink:" : "Drink:",
	"Dessert:" : "Dessert:",
	"Add to Cart" : "Add to Cart",
	"Menu" : "Menu",
	"Burger:" : "Burger :",
	"none" : "none",
	"January" : "January",
	"February" : "February",
	"March" : "March",
	"April" : "April",
	"May" : "May",
	"June" : "June",
	"July" : "July",
	"August" : "August",
	"September" : "September",
	"October" : "October",
	"November" : "November",
	"December" : "December",
	"Today" : "Today",
	"Clear" : "Clear",
	"Mon" : "Mon",
	"Tue" : "Tue",
	"Wed" : "Wed",
	"Fri" : "Fri",
	"Thu" : "Thu",
	"Sat" : "Sat",
	"Sun" : "Sun",
	"You might want to order something before considering checkout." : "You might want to order something before considering checkout.",
	"Your basket is too old, please go back to home and make a new one." : "Your basket is too old, please go back to home and make a new one.",
	"Communication server fail, are you connected to the Internet?" : "Communication server fail, are you connected to the Internet?",
	"You must use a recent device to use this service." : "You must use a recent device to use this service.",
	"Cannot load data, are you connected to the Internet?" : "Cannot load data, are you connected to the Internet?",
	"burger + side + drink"  : "Petit menu: burger + side + drink",
	"burger + side + drink + dessert"  : "Grand menu: burger + side + drink + dessert",
	"Select, purchase and come pick up your order at the time of your choice!" : "Select, purchase and come pick up your order at the time of your choice!", 
	"Hank, 55 rue des Archives 75003 Paris, open 7/7 from 12h to 22h." : "Hank, 55 rue des Archives 75003 Paris, open 7/7 from 12h to 22h."
}

var date_format = 'yyyy-mm-dd';
var lang = localStorage["lang"];
if(lang =='fr') {
	var date_format = 'dd/mm/yyyy';
	var dico = dico_fr;
}

$.i18n.load(dico);
